# Generated by Django 6.0.4 on 2026-05-01 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
        ("intake", "0005_intakesubmission_score_access_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("do_not_bring_up", "Do Not Bring Up"),
                            ("call_prep", "Call Prep"),
                            ("follow_up", "Follow Up"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoverageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("dental", "Dental"),
                            ("vision", "Vision"),
                            ("life", "Life"),
                            ("auto_home", "Auto + Home"),
                            ("homeowners", "Homeowners"),
                            ("umbrella", "Umbrella"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=255)),
                ("plan_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("gap", "Gap"),
                            ("unknown", "Unknown"),
                            ("referral_opportunity", "Referral Opportunity"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("gap_label", models.CharField(blank=True, max_length=255)),
                (
                    "deductible",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "premium",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("actor_type", models.CharField(blank=True, max_length=50)),
                ("actor_name", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="PreCallSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField(blank=True)),
                ("avery_read", models.BooleanField(blank=True, null=True)),
                ("talking_point_order", models.JSONField(blank=True, null=True)),
                ("do_not_bring_up", models.JSONField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="customerrecord",
            name="avg_gap_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="customerrecord",
            name="client_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrecord",
            name="last_submission_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("prospect", "Prospect"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="customerrecord",
            index=models.Index(
                fields=["agent", "status"], name="customers_c_agent_i_f80964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerrecord",
            index=models.Index(
                fields=["last_submission_at"], name="customers_c_last_su_6122f8_idx"
            ),
        ),
        migrations.AddField(
            model_name="agentnote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_agent_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentnote",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_notes",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="agentnote",
            name="intake_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_notes",
                to="intake.intakesubmission",
            ),
        ),
        migrations.AddField(
            model_name="coverageitem",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coverage_items",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="coverageitem",
            name="household_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coverage_items",
                to="intake.householdmember",
            ),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="customeractivity",
            name="intake_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_activities",
                to="intake.intakesubmission",
            ),
        ),
        migrations.AddField(
            model_name="precallsummary",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pre_call_summaries",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="precallsummary",
            name="intake_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pre_call_summaries",
                to="intake.intakesubmission",
            ),
        ),
        migrations.AddIndex(
            model_name="agentnote",
            index=models.Index(
                fields=["customer", "note_type"], name="customers_a_custome_07abe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentnote",
            index=models.Index(
                fields=["intake_session"], name="customers_a_intake__0bf11e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coverageitem",
            index=models.Index(
                fields=["customer", "status"], name="customers_c_custome_320a0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coverageitem",
            index=models.Index(
                fields=["household_member"], name="customers_c_househo_0edb3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeractivity",
            index=models.Index(
                fields=["customer", "created_at"], name="customers_c_custome_9b78c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customeractivity",
            index=models.Index(
                fields=["intake_session"], name="customers_c_intake__430d46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precallsummary",
            index=models.Index(
                fields=["customer", "generated_at"],
                name="customers_p_custome_da56a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="precallsummary",
            index=models.Index(
                fields=["intake_session"], name="customers_p_intake__d889a7_idx"
            ),
        ),
    ]
