# Generated by Django 6.0.4 on 2026-05-01 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_agentnote_coverageitem_customeractivity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precallsummary",
            name="avery_read",
            field=models.TextField(blank=True, null=True),
        ),
    ]
