# Generated by Django 6.0.4 on 2026-05-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_agentnote_coverageitem_customeractivity_and_more"),
        ("gap_scoring", "0001_initial"),
        ("intake", "0005_intakesubmission_score_access_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TalkingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("priority", models.IntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("hook", models.TextField(blank=True)),
                ("suggested_script", models.TextField(blank=True)),
                ("quick_facts", models.JSONField(blank=True, null=True)),
                ("related_finding_ids", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("dismissed", "Dismissed"),
                            ("used", "Used"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="gapfinding",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gapfinding",
            name="finding_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="gapfinding",
            name="source_answer_ids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gapfinding",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("dismissed", "Dismissed"),
                    ("resolved", "Resolved"),
                ],
                db_index=True,
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gapfinding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gapfinding",
            name="assigned_to",
            field=models.CharField(
                choices=[
                    ("hutchins", "Hutchins"),
                    ("partner_referral", "Partner Referral"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gapfinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="gapfinding",
            name="severity",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="gapfinding",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gap_findings",
                to="intake.intakesubmission",
            ),
        ),
        migrations.AddIndex(
            model_name="gapfinding",
            index=models.Index(
                fields=["customer", "status"], name="gap_scoring_custome_d761be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gapfinding",
            index=models.Index(
                fields=["submission"], name="gap_scoring_submiss_c6365e_idx"
            ),
        ),
        migrations.AddField(
            model_name="talkingpoint",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talking_points",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="talkingpoint",
            name="intake_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="talking_points",
                to="intake.intakesubmission",
            ),
        ),
        migrations.AddIndex(
            model_name="talkingpoint",
            index=models.Index(
                fields=["customer", "priority"], name="gap_scoring_custome_f5b564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="talkingpoint",
            index=models.Index(
                fields=["intake_session"], name="gap_scoring_intake__f4b9eb_idx"
            ),
        ),
    ]
