# Generated by Django 6.0.4 on 2026-05-01 04:23

from django.db import migrations, models


def seed_defaults(apps, schema_editor):
    RuleConfig = apps.get_model("gap_scoring", "RuleConfig")
    ScoringWeight = apps.get_model("gap_scoring", "ScoringWeight")
    TalkingPointTemplate = apps.get_model("gap_scoring", "TalkingPointTemplate")

    rule_defaults = {
        "health_gap": ("Household members need coverage with no current health plan", "health", "critical", 30),
        "aca_follow_up": ("Marketplace / ACA follow-up requested", "health", "medium", 10),
        "prescription_risk": ("Prescriptions need plan review", "health", "high", 15),
        "vision_gap": ("Family vision coverage opportunity", "health", "medium", 10),
        "dental_gap": ("Family dental coverage opportunity", "health", "medium", 10),
        "life_gap": ("Family life insurance coverage opportunity", "life", "high", 20),
        "spouse_uncovered": ("Spouse may need coverage", "health", "high", 20),
        "homeowners_gap": ("Homeowner without homeowners insurance", "home", "high", 20),
        "rental_property": ("Rental property ownership", "home", "medium", 10),
        "umbrella_gap": ("Assets over $250k without umbrella coverage", "umbrella", "high", 20),
        "liability_without_umbrella": ("Extra liability risk without umbrella coverage", "umbrella", "high", 20),
        "auto_liability_review": ("Auto liability limits uncertain/low", "auto", "medium", 10),
    }
    for rule_key, (title, category, severity, points) in rule_defaults.items():
        RuleConfig.objects.update_or_create(
            rule_key=rule_key,
            defaults={
                "title": title,
                "description": "",
                "category": category,
                "enabled": True,
                "severity": severity,
                "points": points,
                "config": {},
            },
        )
        ScoringWeight.objects.update_or_create(
            weight_key=rule_key,
            defaults={
                "label": title,
                "value": points,
                "enabled": True,
            },
        )

    template_defaults = {
        "health_gap": ("Health coverage for household members", "health", "Some household members may need coverage.", "I saw there may be a coverage gap for someone in the household. Want to start there?"),
        "aca_follow_up": ("Marketplace / ACA follow-up", "health", "Customer appears open to ACA/Marketplace help.", "You mentioned wanting help with health coverage. I can walk through Marketplace options with you."),
        "vision_gap": ("Vision plan for the family", "health", "Family vision coverage may be missing.", "Would adding vision for the family make sense if the monthly cost is reasonable?"),
        "dental_gap": ("Dental plan for the family", "health", "Family dental coverage may be missing.", "Do you want me to check dental options while we review health coverage?"),
        "life_gap": ("Term life protection", "life", "Household has spouse/dependents and may need life coverage.", "Have you thought about your own coverage now that others depend on your income?"),
        "homeowners_gap": ("Homeowners coverage review", "property", "Customer may own a home without homeowners coverage.", "I noticed you may own your home. Do you already have homeowners coverage in place?"),
        "umbrella_gap": ("Umbrella liability coverage", "referral", "Assets or liability exposure may justify umbrella coverage.", "With your assets and liability exposure, umbrella coverage may be worth reviewing."),
        "liability_without_umbrella": ("Umbrella liability coverage", "referral", "Assets or liability exposure may justify umbrella coverage.", "With your assets and liability exposure, umbrella coverage may be worth reviewing."),
        "rental_property": ("Rental property coverage review", "referral", "Rental property ownership creates a coverage review opportunity.", "Do you have landlord or rental property coverage set up for that property?"),
        "auto_liability_review": ("Auto liability limit review", "referral", "Auto liability limits may be low or unknown.", "It may be worth checking whether your auto liability limits are high enough."),
    }
    for template_key, (title, category, hook, script) in template_defaults.items():
        TalkingPointTemplate.objects.update_or_create(
            template_key=template_key,
            defaults={
                "finding_type": template_key,
                "title": title,
                "category": category,
                "hook": hook,
                "suggested_script": script,
                "quick_facts_template": [],
                "enabled": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("gap_scoring", "0002_talkingpoint_gapfinding_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gapfinding",
            name="is_generated",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.CreateModel(
            name="ProductAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(db_index=True, max_length=2)),
                ("coverage_type", models.CharField(db_index=True, max_length=80)),
                ("carrier", models.CharField(db_index=True, max_length=255)),
                ("product_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("limited", "Limited"),
                            ("unavailable", "Unavailable"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "coverage_type", "carrier"],
                        name="gap_scoring_state_5b224f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RuleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_key", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("config", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["rule_key", "enabled"],
                        name="gap_scoring_rule_ke_b4f519_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoringWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_key", models.CharField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=255)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["weight_key", "enabled"],
                        name="gap_scoring_weight__fba6e1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TalkingPointTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_key", models.CharField(max_length=100, unique=True)),
                ("finding_type", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("hook", models.TextField(blank=True)),
                ("suggested_script", models.TextField(blank=True)),
                ("quick_facts_template", models.JSONField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["finding_type", "enabled"],
                        name="gap_scoring_finding_bc6902_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_defaults, noop_reverse),
    ]
