# Generated by Django 6.0.4 on 2026-04-27 03:52

import apps.questionnaires.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.questionnaires.models._default_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("include_health", models.BooleanField(default=True)),
                ("include_life", models.BooleanField(default=True)),
                ("include_auto", models.BooleanField(default=True)),
                ("include_home", models.BooleanField(default=True)),
                ("include_umbrella", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire_links",
                        to="agents.agentprofile",
                    ),
                ),
            ],
        ),
    ]
