# Generated by Django 6.0.4 on 2026-04-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_householdmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="takes_prescriptions",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PrescriptionMedication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_id", models.CharField(blank=True, max_length=100)),
                ("drug_name", models.CharField(max_length=255)),
                ("normalized_drug_name", models.CharField(blank=True, max_length=255)),
                ("source", models.CharField(default="rxterms", max_length=50)),
                ("dosage_strength", models.CharField(blank=True, max_length=100)),
                ("frequency", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "household_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_medications",
                        to="intake.householdmember",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription_medications",
                        to="intake.intakesubmission",
                    ),
                ),
            ],
        ),
    ]
