# Generated by Django 6.0.4 on 2026-05-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0002_agentnote_coverageitem_customeractivity_and_more"),
        ("intake", "0005_intakesubmission_score_access_token_and_more"),
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="householdmember",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="household_members",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="has_prescriptions",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="needs_health_coverage",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="householdmember",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="intakeanswer",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intake_answers",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="intakeanswer",
            name="normalized_value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intakeanswer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="intakesubmission",
            name="public_token",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="intakesubmission",
            name="source",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("primary", "Primary"),
                    ("spouse", "Spouse"),
                    ("dependent", "Dependent"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="intakeanswer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="intakeanswer",
            name="question_text",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="intakesubmission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="intakesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("in_progress", "In Progress"),
                    ("submitted", "Submitted"),
                    ("reviewed", "Reviewed"),
                    ("archived", "Archived"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="intakeanswer",
            index=models.Index(
                fields=["submission", "question_key"],
                name="intake_inta_submiss_bf0b7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intakeanswer",
            index=models.Index(
                fields=["customer"], name="intake_inta_custome_46166f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intakesubmission",
            index=models.Index(
                fields=["customer", "status"], name="intake_inta_custome_13553e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intakesubmission",
            index=models.Index(
                fields=["agent", "created_at"], name="intake_inta_agent_i_8594da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intakesubmission",
            index=models.Index(
                fields=["submitted_at"], name="intake_inta_submitt_2751be_idx"
            ),
        ),
    ]
