# Generated by Django 6.0.4 on 2026-05-01 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0006_householdmember_age_householdmember_customer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intakesubmission",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="intakesubmission",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("unreviewed", "Unreviewed"),
                    ("reviewed", "Reviewed"),
                    ("needs_follow_up", "Needs Follow Up"),
                ],
                db_index=True,
                default="unreviewed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="intakesubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intakesubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_intake_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
