# Generated by Django 6.0.4 on 2026-04-27 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        ("customers", "0001_initial"),
        ("questionnaires", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consent_terms", models.BooleanField(default=False)),
                ("consent_privacy", models.BooleanField(default=False)),
                ("consent_contact", models.BooleanField(default=False)),
                ("consent_referral_sharing", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="agents.agentprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="customers.customerrecord",
                    ),
                ),
                (
                    "questionnaire_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="questionnaires.questionnairelink",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntakeAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=32)),
                ("question_key", models.CharField(max_length=128)),
                ("question_text", models.CharField(max_length=512)),
                ("answer_value", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="intake.intakesubmission",
                    ),
                ),
            ],
        ),
    ]
