# Generated by Django 6.0.4 on 2026-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakeanswer",
            name="supports",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="intakeanswer",
            name="module",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
