# Generated by Django 6.0.4 on 2026-04-27 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_intakeanswer_supports_alter_intakeanswer_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("spouse", "Spouse"),
                            ("dependent", "Dependent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("date_of_birth", models.DateField()),
                ("needs_coverage", models.BooleanField(default=True)),
                ("other_coverage_access", models.BooleanField(default=False)),
                ("legal_parent_guardian_under_19", models.BooleanField(default=False)),
                ("claimed_tax_dependent", models.BooleanField(default=False)),
                ("pregnant", models.BooleanField(default=False)),
                ("tobacco_user", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_members",
                        to="intake.intakesubmission",
                    ),
                ),
            ],
        ),
    ]
