# Generated by Django 6.0.4 on 2026-04-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0004_householdmember_takes_prescriptions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakesubmission",
            name="score_access_token",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="intakesubmission",
            name="score_viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
