# Generated by Django 6.0.4 on 2026-04-27 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("life", "Life"),
                            ("auto", "Auto"),
                            ("home", "Home"),
                            ("umbrella", "Umbrella"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("possible_opportunity", "Possible Opportunity"),
                            ("ready_to_refer", "Ready To Refer"),
                            ("referred", "Referred"),
                            ("closed", "Closed"),
                        ],
                        default="possible_opportunity",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_opportunities",
                        to="customers.customerrecord",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_opportunities",
                        to="intake.intakesubmission",
                    ),
                ),
            ],
        ),
    ]
