# Generated by Django 6.0.4 on 2026-05-01 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_precallsummary_avery_read"),
        ("questionnaires", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairelink",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questionnaire_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questionnaire_links",
                to="customers.customerrecord",
            ),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="delivery_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="open_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnairelink",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("sent", "Sent"),
                    ("started", "Started"),
                    ("submitted", "Submitted"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
    ]
