# Generated by Django 6.0.4 on 2026-05-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0002_questionnairelink_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnairelink",
            name="module_order",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
