# Generated by Django 6.0.4 on 2026-04-27 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GapFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("life", "Life"),
                            ("auto", "Auto"),
                            ("home", "Home"),
                            ("umbrella", "Umbrella"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.CharField(
                        choices=[
                            ("hutchins", "Hutchins"),
                            ("partner_referral", "Partner Referral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gap_findings",
                        to="customers.customerrecord",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gap_findings",
                        to="intake.intakesubmission",
                    ),
                ),
            ],
        ),
    ]
